#!/bin/bash

# Convert Earth Gravity Model (EGM96 and EGM2008) data to NetCDF format
# Data source: https://www.agisoft.com/downloads/geoids/

if ! command -v gdal_translate &>/dev/null; then
    echo 'gdal_translate command not found. Can be installed with "conda install gdal" or "conda env create -f conda-gmted2nc-environment.yml"'
    exit 1
fi

# Input and output directories
srcdir=../inputs
outdir=../netcdf

ncvarname=geoid_altitude

# Source versions and resolutions
sources='egm96_15 egm2008_25' #egm2008_1

for src in ${sources}; do 

  echo ${src}

  # Source file
  srcfile=${srcdir}/us_nga_${src}.tif

  # Output file
  case ${src} in 
    egm96_15)
      version=EGM96
      res=15arcmin
      remap=true
      ;;
    egm2008_25)
      version=EGM2008
      res=2p5arcmin
      remap=false
      ;;
    egm2008_1)
      version=EGM2008
      res=1arcmin
      remap=false
      ;;
    ?)
      echo "Invalid souce name: ${src}."
      exit 1
      ;;
  esac
  outfile=${outdir}/${version}_${res}.nc4

  # Download source data, if needed
  if [ ! -f ${srcfile} ]; then 
    echo 'Downloading source data...'
    (cd ${srcdir}; curl -O https://s3-eu-west-1.amazonaws.com/download.agisoft.com/gtg/$(basename ${srcfile}))
  fi

  # Convert to netCDF with GDAL
  echo 'Converting to netCDF...'
  gdal_translate -of NetCDF ${srcfile} ${srcfile}.tmp.nc

  # Add bounds for latitude, longitude
  ncap2 -O -h -s 'defdim("nb",2); lon_bnds=make_bounds(lon,$nb,"lon_bnds"); lat_bnds=make_bounds(lat,$nb,"lat_bnds")' $srcfile.tmp.nc $srcfile.tmp.nc

  # Compress and refine
  echo 'Compressing...'
  # Round to nearest cm (data accuracy) and store as a short int
  ncap2 -O -h -s 'Band1=short(Band1*100); Band1@scale_factor=0.01; Band1@add_offset=0.0' $srcfile.tmp.nc $srcfile.tmp.nc
  # Lossless compression
  ncks -O -h -7 -L 2 --cnk_dmn lon,1500 --cnk_dmn lat,1500 $srcfile.tmp.nc $outfile

  # Remove temporary file
  rm $srcfile.tmp.nc

  # Add attributes
  echo 'Renaming variables, attributes...'
  ncrename -O -h -v Band1,${ncvarname} $outfile
  ncatted -O -h -a long_name,${ncvarname},o,c,"altitude of the geoid above the reference ellipsoid (WGS84)" $outfile
  ncatted -O -h -a units,${ncvarname},o,c,'m' $outfile
  ncatted -O -h -a standard_name,${ncvarname},o,c,"geoid_height_above_reference_ellipsoid" $outfile
  ncatted -O -h -a Source,global,o,c,"EGM96, EGM2008 data source: https://www.agisoft.com/downloads/geoids/ "  $outfile
  ncatted -O -h -a Author,global,o,c,'Converted from GeoTIFF using egm2nc script from Christopher D. Holmes, cdholmes@fsu.edu'  $outfile

  if [ "${remap}" = true ]; then
    # Interpolate to the GMTED2010 30 arc-sec grid
    echo 'Interpolate to GMTED2010 resolution... (This may take 30 minutes or more)'
    outfile_hires=${outdir}/${version}_30arcsec.nc4
    cdo remapbil,${outdir}/GMTED2010_mean_30arcsec.nc4 ${outfile} ${outfile_hires}
    # linear inverse distance weighting (similar to bilinear) and pure nco
    # ncremap -a nco_idw -xtr_xpn=1.0 -s ${outfile} -d GMTED2010_mean_30arcsec.nc4 ${outfile_hires}
  fi

done

